feat: Use poetry-core, not poetry, as build backend
Before, if I tried to install splink in editable mode, I would get

ERROR: Project file:///Users/nickcrews/Documents/projects/splink has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

Installing in editable mode is important because for rapid
development I have my projects organized as
projects/my_app and projects/splink,
and in my_app I run `pip install -e ../splink`, and then
I am free to hack on my fork of splink
and verify that the changes still work.

poetry-core should work just fine, will be better maintained,
and should be faster:
https://github.com/python-poetry/poetry-core